FROM phusion/holy-build-box-64

RUN curl https://nodejs.org/dist/v6.5.0/node-v6.5.0-linux-x64.tar.gz -o /tmp/node-v6.5.0-linux-x64.tar.gz && ( cd /opt && tar xvzf /tmp/node-v6.5.0-linux-x64.tar.gz ; ) && rm /tmp/node-v6.5.0-linux-x64.tar.gz

RUN { echo '[ "x$CCACHE" = xtrue ] || return' ; echo ' [ -d /vagrant/cache ] || mkdir /vagrant/cache' ; echo 'export CC="ccache gcc" CXX="ccache g++" CCACHE_DIR="/vagrant/cache"' ; } > /ccache.sh

VOLUME /vagrant

ENV PYTHON python
CMD source /hbb_exe/activate ; cd /vagrant ; source /ccache.sh ; env PATH="/opt/node-v6.5.0-linux-x64/bin:${PATH}" npm run build && strip --strip-all out.nex
