FROM centos:6.7

RUN yum groupinstall -y 'Development Tools'
RUN yum install -y tar xz
RUN curl https://people.centos.org/tru/devtools-2/devtools-2.repo -o /etc/yum.repos.d/devtools-2.repo
RUN yum install -y devtoolset-2-gcc devtoolset-2-binutils devtoolset-2-gcc-c++
RUN curl https://nodejs.org/dist/v6.5.0/node-v6.5.0-linux-x64.tar.xz -o /tmp/node-v6.5.0-linux-x64.tar.xz && ( cd /opt && tar xvJf /tmp/node-v6.5.0-linux-x64.tar.xz ; ) && rm /tmp/node-v6.5.0-linux-x64.tar.xz

VOLUME /vagrant

CMD cd /vagrant ; exec env PATH="/opt/rh/devtoolset-2/root/usr/bin:/opt/node-v6.5.0-linux-x64/bin:${PATH}" npm run build
